{{- if .Values.manager.enabled -}}
{{- if .Values.generateSecret }}
{{- $cn := "neuvector" }}
{{- $ca := genCA (printf "%s-ca" "neuvector") (.Values.defaultValidityPeriod | int) -}}
{{- $cert := genSignedCert $cn nil (list $cn) (.Values.defaultValidityPeriod | int) $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-manager-secret
type: Opaque
data:
  ssl-cert.key: {{ include "neuvector.secrets.lookup" (dict "namespace" .Release.Namespace "secret" "neuvector-manager-secret" "key" "ssl-cert.key" "defaultValue" $cert.Key) }}
  ssl-cert.pem: {{ include "neuvector.secrets.lookup" (dict "namespace" .Release.Namespace "secret" "neuvector-manager-secret" "key" "ssl-cert.pem" "defaultValue" $cert.Cert) }}
---
{{- end }}
{{- end }}